
%----    Basic packages    ----%
\documentclass{article}  

\usepackage{hyperref}

%----    Settings    ----%

<<setup, include=FALSE>>=
knitr::opts_chunk$set(echo = TRUE)
@

% Document title info
\title{Reviewdown Test}
\author{reviewdown}
% \date{}
\begin{document}

%----    Title    ----%

\maketitle

\section{R and \LaTeX}

This is an Rnw document. \LaTeX is a (\textit{not so}) simple formatting syntax for authoring PDF documents. For more details on using \LaTeX see \url{https://www.overleaf.com/learn}.

<<cars>>=
summary(cars)
@

\end{document}
