\section{R and \LaTeX}

This is an Rnw document. \LaTeX is a (\textit{not so}) simple formatting syntax for authoring PDF documents. For more details on using \LaTeX see \url{https://www.overleaf.com/learn}.


Tryng to mess up \LaTeX \\documentclass{ 
When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this: \\begin{document}
